version: '3.4'

services:
  testdrivendevelopmentapp:
    image: ${DOCKER_REGISTRY-}testdrivendevelopmentapp
    build:
      context: .
      dockerfile: TestDrivenDevelopmentApp/Dockerfile
    environment:
      - "ConnectionStrings:DefaultConnection=Server=sqlserver-db;Database=Test_Driven_Development;User=sa;Password=YourStrong!Passw0rd"
      - authmanagement_url=https://authmanagement:5001
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - redis

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-db
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: YourStrong!Passw0rd
    ports:
      - "1433:1433"

  authmanagement:
    image: ${DOCKER_REGISTRY-}authmanagement
    build:
      context: .
      dockerfile: AuthManagement/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./.containers/redis/data:/data