#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["TestDrivenDevelopmentApp/TestDrivenDevelopmentApp.csproj", "TestDrivenDevelopmentApp/"]
RUN dotnet restore "./TestDrivenDevelopmentApp/TestDrivenDevelopmentApp.csproj"
COPY . .
WORKDIR "/src/TestDrivenDevelopmentApp"
RUN dotnet build "./TestDrivenDevelopmentApp.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Publish the app
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TestDrivenDevelopmentApp.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Final stage/image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestDrivenDevelopmentApp.dll"]